# Base image: Node.js 18
???

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the dependencies file to the working directory
???

# Install dependencies
???

# Copy the content of the local src directory to the working directory
COPY . .

# Specify the command to run on container start
CMD ["npm", "start"]
